baseURL = "https://novaclearnscyber.github.io/blog/"
languageCode = 'ro-ro'
title = 'Cyber Blog-ul lui Novac'

[taxonomies]
  category = "categories"
  tag = "tags"

canonifyURLs = true
relativeURLs = false

[pagination]
  pagerSize = 9999

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[module]
  [[module.imports]]
    path = "github.com/hugo-sid/hugo-blog-awesome"

  [[module.mounts]]
    source = 'content'
    target = 'content'

  [[module.mounts]]
    source = 'static'
    target = 'static'
  [[module.mounts]]
    source = 'assets'
    target = 'assets'
  [[module.mounts]]
    source = 'layouts'
    target = 'layouts'


[params]
  banner = "siteBackcopy.png"
  banner_height = "450px"
  defaultColor = "dark"

[menu]
  [[menu.main]]
    name = "Categories"
    url = "/categories/"
    weight = 10
